### ISSUE TITLE
gulp task failed

### ISSUE THREAD

**Issue by tn** [jhendley25/generator-dyno#40]
```bash
..EXAMPLE/node_modules/debowerify/node_modules/bower/node_modules/q/q.js:126
                    throw e;
                          ^
SyntaxError: Unexpected token ,
    at Object.parse (native)
    at /..EXAMPLE/node_modules/debowerify/node_modules/bower/node_modules/bower-json/lib/json.js:41:29
    at fs.js:334:14
    at /..EXAMPLE/node_modules/debowerify/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:104:5
    at /..EXAMPLE/node_modules/debowerify/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:104:5
    at /..EXAMPLE/node_modules/debowerify/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Steps to reproduce**:
* Run `yo dyno`
* Uncheck `underscore`
* Check `JQuery`
* Install

Then you can see that the bower.json has a syntax error
```json
{
  "name": "EXAMPLE",
  "version": "0.0.0",
  "dependencies": {,
    "jquery": "*"
    },
  "devDependencies": {  }
}
```
Run `gulp` to see error message above. Thanks

**Comment by jhendley25** [comment]
Thanks for the heads up @tn
